name: untitled
description: "A new Flutter project."

# The following line helps with publishing
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0  # Flutter 3.24+ uses Dart 3.5+, safe and recommended

dependencies:
  flutter:
    sdk: flutter

  # Core
  supabase_flutter: ^2.6.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  flutter_map: ^8.2.2      # The free map widget
  latlong2: ^0.9.1          # Helper for coordinates
  geocoding: ^3.0.0
  geolocator: ^13.0.0


  # Auth
  sign_in_with_apple: ^6.1.1
  google_sign_in: ^6.2.1
  crypto: ^3.0.3

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  # Add your assets here
