name: untitled
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  app_links: ^3.5.0

  firebase_core: ^3.6.0          # check latest
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter

  # Core
  supabase_flutter: ^2.6.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.3.0
  geolocator: ^14.0.2
  time_picker_spinner: ^1.0.0


  # Auth
  sign_in_with_apple: ^6.1.1
  google_sign_in: ^6.2.1
  crypto: ^3.0.3

  # Icons
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.1.1
  fl_chart: ^1.1.1
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  # Add your assets here
